config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  resource :author, only: %i(show update edit)

  resources :channels

  resources :posts do
    member do
      get :preview
      post :like
      post :unlike
    end
  end

  get '/login' => "logins#new", as: :login
  post '/login' => "logins#new"
  get '/login/:token' => "logins#create", as: :magic_link
  get '/logout' => "logins#destroy", as: :logout

  # Bot redirects
  get 'wp-login.php' => redirect('/')
  get 'authors/wp-login.php' => redirect('/')

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    redirect_to root_path and return if current_user
    if request.post?
      if valid_email?
        auth = Authentication.create(email: login_params[:email])
        LoginMailer.send_magic_link(auth).deliver_later
        render 'confirm'
      else
        flash[:error] = "Please supply a valid email address."
      end
    end
  end

  def create
    if !params[:token].blank? && authentication = Authentication.find(params[:token])
      session[:current_user] = authentication.user
      redirect_to root_path
    else
      session[:current_user] = nil if current_user
      render 'error'
    end
  end

  def destroy
    session[:current_user] = nil
    redirect_to root_path
  end

  private

  def login_params
    params.require(:login).permit(:email)
  end

  def valid_email?
    login_params[:email] =~ /[^\s]@[^\s]/
  end

end

app/views/logins/confirm.html.haml
.row
  .col-md-6.offset-md-3
    %h1 Sign In / Register to Ahhlife
    .my-2
      = image_tag 'mail_sent.gif'

    %h2 An email is on its way
    %p
      We sent an email to <strong>#{@email}</strong>. If you entered the incorrect email no big deal, just hit the back button and try again.

    %p
      The link expires in an hour so make sure to use it soon.

    %p
      %strong Go check your email!!!

app/views/logins/error.html.haml
.row
  .col-md-6.offset-md-3
    %h1 Uh-oh that link did not work
    .my-2
      = image_tag 'sadpanda.gif', class: 'img-fluid'

    %h2 Probably you've used it to login already or it's too old
    %p
      We expire login links after an hour and also after you use them once, to
      make sure that we keep access to your journal private from nosy people and hackers.

    %p
      %strong
        You can
        = link_to "request a fresh login link", login_url

app/views/logins/new.html.haml
.row
  .col-md-6.offset-md-3
    %h1 Sign In

    = simple_form_for :login do |f|
      = f.input :email, type: 'email', label: "Enter your email and we'll send you a link to access the app", autofocus: true, required: true
      = f.submit "Give me a sign in link", class: "btn btn-primary btn-block"