config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  resource :author, only: %i(show update edit)

  resources :channels

  resources :posts do
    member do
      get :preview
      post :like
      post :unlike
    end
  end

  get '/login' => "logins#new", as: :login
  post '/login' => "logins#new"
  get '/login/:token' => "logins#create", as: :magic_link
  get '/logout' => "logins#destroy", as: :logout

  # Bot redirects
  get 'wp-login.php' => redirect('/')
  get 'authors/wp-login.php' => redirect('/')

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title Estilista TIL Server by Obie Fernandez

    = csrf_meta_tags

    %meta(name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1")

    %link(href='//fonts.googleapis.com/css?family=Raleway:700,900' rel='stylesheet' type='text/css')
    %link(href='//fonts.googleapis.com/css?family=Lora:400,700italic,700,400italic' rel='stylesheet' type='text/css')

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

    =# favicon_link_tag 'favicon.png'

    = yield :head

    %meta(name="twitter:card" content="summary_large_image")
    %meta(name="twitter:site" content="@hashrockettil")
    %meta(name="twitter:creator" content="@obie")
    %meta(name="twitter:title" content="Today I Learned: a Hashrocket Project")
    %meta(name="twitter:description" content="TIL is an open-source project by Hashrocket that exists to catalogue the sharing & accumulation of knowledge as it happens day-to-day.")
    %meta(name="twitter:image" content="https://til.hashrocket.com/assets/til_twittercard.png")

    = yield :canonical

  %body
    %nav.admin_panel
      %ul
        - if current_user
          %li= link_to current_user.email, current_user
          %li= link_to "Sign Out", logout_path
          %li= link_to "Create Post", new_post_path
          %li= link_to "Drafts", drafts_path
          %li= link_to "Profile", edit_profile_path
        - else
          %li= link_to "Login", login_path


    %header.site_head
      %div
        %h1= link_to "TIL", root_path

    = render 'shared/flash'

    %main= yield

    %nav.site_nav
      %ul
        %li.site_nav__about
          = link_to "?", "#", class: "site_nav__link"
          .site_nav__toggle
            .copy
              TIL about tbd
              %ul.social
                %li= link_to "/hashrockettil", "https://twitter.com/hashrockettil", class: "social_twitter"

        %li.site_nav__search
          = link_to "search", "#", class: "site_nav__link"
          .site_nav__toggle>
            = form_tag root_path, method: 'get' do
              = search_field_tag :q
              = button_tag 'Search', name: nil

app/views/layouts/ui_application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title= "#{SITE_NAME}"
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
    %meta(name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1")
    %link(href='http://fonts.googleapis.com/css?family=Raleway:700,900' rel='stylesheet' type='text/css')
    %link(href='http://fonts.googleapis.com/css?family=Lora:400,700italic,700,400italic|Limelight' rel='stylesheet' type='text/css')
    = yield :head
  %body

    .sticker
      1000
      %span Posts

    %nav.admin_panel
      %ul
        %li= link_to Phil.name, "#"
        %li= link_to "create post", "#"
        %li= link_to "drafts", "#"
        %li= link_to "sign out", "#"

    %header.site_head
      %div
        %h1= link_to "Today I learned", "#"
        %h2= link_to "A Hashrocket project", "#"

    -# #flash
    -#   %p.notice= Phil.words 20
    -#   %p.error= Phil.words 20

    %main= yield

    %nav.site_nav
      %ul
        %li.site_nav__about
          = link_to "About TIL", "#", class: "site_nav__link"
          .site_nav__toggle
            .copy
              :markdown
                TIL is an open-source project by
                [Hashrocket](https://hashrocket.com) that exists to catalogue
                the sharing & accumulation of knowledge as it happens
                day-to-day. Posts have a 200-word limit, and posting is open to
                any Rocketeer as well as selected friends of Hashrocket. We
                hope you enjoy learning along with us.
              %ul.social
                %li= link_to "/hashrockettil", "http://twitter.com/hashrockettil", class: "social_twitter"
                %li= link_to "/hashrockettil", "http://github.com/hashrockettil", class: "social_github"
        %li.site_nav__statistics
          = link_to "statistics", "#", class: "site_nav__link"
        %li.site_nav__search
          %form<
            = link_to "search", "#", class: "site_nav__link"
            .site_nav__toggle
              %input(type='search')
              %input(type='submit' value='Search')

    = javascript_include_tag 'application'